apiVersion: v1
kind: Namespace
metadata:
  name: nfs-server

---

kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: nfs-server
spec:
  clusterIP: 10.96.254.8
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mydata
      volumes:
        - name: mydata
          #emptyDir: {}
          hostPath:
            path: /tmp/k8s-nfs
