apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: test2
  namespace: default
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - curl http://ericyeh.tk:1080/trainer_kubeflow.py -o /trainer.py && python
              /trainer.py
            command:
            - /bin/bash
            - -c
            image: tensorflow/tensorflow:1.9.0
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
          restartPolicy: OnFailure
    Worker:
      replicas: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - curl http://ericyeh.tk:1080/trainer_kubeflow.py -o /trainer.py && python
              /trainer.py
            command:
            - /bin/bash
            - -c
            image: tensorflow/tensorflow:1.9.0
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
          restartPolicy: OnFailure
