apiVersion: v1
kind: Service
metadata:
  name: tf-service
  labels:
    app: tf-service
spec:
  type: ClusterIP
  ports:
  - name: tf-server
    port: 2222
    targetPort: 2222
  clusterIP: None
  selector:
    tf: worker

---

apiVersion: v1
kind: Pod
metadata:
  name: ps0
  labels:
    tf: worker
spec:
  subdomain: tf-service
  hostname: ps0
  restartPolicy: Never
  containers:
  - name: tensorflow
    image: tensorflow/tensorflow:1.9.0
    ports:
    - name: tf-server
      containerPort: 2222
    env:
    - name: TASK_INDEX
      value: "0"
    command: ["/bin/bash", "-c"]
    args: ["
    curl http://ericyeh.tk:1080/trainer.py -o /trainer.py && \
    python /trainer.py \
    --ps_hosts=ps0.tf-service.default.svc.cluster.local:2222 \
    --worker_hosts=worker0.tf-service.default.svc.cluster.local:2222,worker1.tf-service.default.svc.cluster.local:2222,worker2.tf-service.default.svc.cluster.local:2222 \
    --job_name=ps --task_index=$TASK_INDEX
    "]
