apiVersion: v1
kind: Pod
metadata:
  name: volume
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: test-container
    command:
    - "sh"
    args:
    - "-c"
    - "touch /cache/hello.txt && ls -l /cache"
    volumeMounts:
    - mountPath: /cache
      name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
  nodeSelector:
    fortest: "true"
