apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-echo-hostname
spec:
  selector:
    matchLabels:
      app: echo-hostname
  replicas: 2
  template:
    metadata:
      labels:
        app: echo-hostname
    spec:
      containers:
      - name: nodejs
        image: google/nodejs
        ports:
        - containerPort: 80
        command: ["/bin/bash"]
        args: ["-c", "install_node 8.11.1 && echo \"function r(request,response){response.writeHead(200,{'Content-Type':'text/plain'});response.write(process.env.MYNAME+'_'+process.env.HOSTNAME);response.end('\\n');}require('http').createServer(r).listen(80);\" | node"]
        env:
        - name: MYNAME
          value: echoHostname

---

apiVersion: v1
kind: Service
metadata:
  name: service-echo-hostname
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echo-hostname

