apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-tensorflow-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tensorflow-controller
subjects:
- kind: ServiceAccount
  name: tensorflow-controller
  namespace: default
