apiVersion: v1
kind: Service
metadata:
  name: mongodb-cfgserver
  labels:
    name: mongo
spec:
  ports:
  - port: 27018
    targetPort: 27018
  clusterIP: None
  selector:
    role: mongo-cfgserver

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb-cfgserver
spec:
  serviceName: mongodb-cfgserver
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo-cfgserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo
          command:
            - "mongod"
            - "--configsvr"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
            - "--port"
            - "27018"
            - "--replSet"
            - "configdb"
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
    spec:
      storageClassName: mongo-cfgserver
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
