apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-cfgserver-#
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/mongo-cfgserver-#
  storageClassName: mongo-cfgserver

