apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-08-01T13:28:46Z
  labels:
    group_name: kubeflow.org
    tf-replica-index: "0"
    tf-replica-type: ps
    tf_job_key: new2
  name: new2-ps-0
  namespace: default
  ownerReferences:
  - apiVersion: kubeflow.org/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: TFJob
    name: new2
    uid: d0dc8b3d-958e-11e8-8654-0800276019d7
  resourceVersion: "37575"
  selfLink: /api/v1/namespaces/default/pods/new2-ps-0
  uid: d1105cf7-958e-11e8-8654-0800276019d7
spec:
  containers:
  - args:
    - curl http://ericyeh.tk:1080/trainer_kubeflow.py -o /trainer.py && python /trainer.py
    command:
    - /bin/bash
    - -c
    env:
    - name: TF_CONFIG
      value: '{"cluster":{"ps":["new2-ps-0.default.svc.cluster.local:2222","new2-ps-1.default.svc.cluster.local:2222"],"worker":["new2-worker-0.default.svc.cluster.local:2222","new2-worker-1.default.svc.cluster.local:2222","new2-worker-2.default.svc.cluster.local:2222","new2-worker-3.default.svc.cluster.local:2222","new2-worker-4.default.svc.cluster.local:2222"]},"task":{"type":"ps","index":0}}'
    image: tensorflow/tensorflow:1.9.0
    imagePullPolicy: IfNotPresent
    name: tensorflow
    ports:
    - containerPort: 2222
      name: tfjob-port
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-zrxl4
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-zrxl4
    secret:
      defaultMode: 420
      secretName: default-token-zrxl4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-08-01T13:28:46Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-08-01T13:29:14Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-08-01T13:28:46Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2225c8d7209be249cafd1f4ac513231245708c7b28c413a9ff0492b380dfbe21
    image: tensorflow/tensorflow:1.9.0
    imageID: docker-pullable://tensorflow/tensorflow@sha256:92ad7f5da1f0e7c2c7b714b77b12424ae3d7971510d8ff8673b8b0695c3fd1c9
    lastState: {}
    name: tensorflow
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-08-01T13:29:04Z
  hostIP: 10.0.2.15
  phase: Running
  podIP: 172.17.0.15
  qosClass: BestEffort
  startTime: 2018-08-01T13:28:46Z
