apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-batchd
  namespace: kube-system
  labels:
    chart: kube-arbitrator-0.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-batchd
  template:
    metadata:
      labels:
        app: kube-batchd
    spec:
      serviceAccountName: kar-scheduler
      containers:
      - name: kube-arbitrator
        #image: kubearbitrator/kar-scheduler:0.2
        image: ncy9371/kar-scheduler:20180907-1
        command:
        - /kube-batchd
        args:
        - --logtostderr
        - --v=3
        - --enable-namespace-as-queue
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 2000m
            memory: 2048Mi
