apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-deployment
spec:
  selector:
    matchLabels:
      app: nginx-php
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
        - name: nginx
          image: ncy9371/nginx:1.13.12-eric
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-data
              mountPath: /usr/share/nginx/html
        - name: php
          image: php:7.2.5-fpm
          command: ["php-fpm"]
          volumeMounts:
            - name: html-data
              mountPath: /var/www/html
      volumes:
        - name: html-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
spec:
  type: NodePort
  selector:
    app: nginx-php
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30303
      protocol: TCP
