apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php
  replicas: 5
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: php:7.2.5-fpm
          ports:
            - containerPort: 9000
          command: ["php-fpm"]
          volumeMounts:
            - name: html-data
              mountPath: /var/www/html
      volumes:
        - name: html-data
          persistentVolumeClaim:
            claimName: nfs

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: ClusterIP
  selector:
    app: php
  ports:
    - name: php
      port: 9000
      targetPort: 9000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ncy9371/nginx:1.13.12-outphp
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-data
          persistentVolumeClaim:
            claimName: nfs

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30303
      protocol: TCP